# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToDolist(object):
    def setupUi(self, ToDolist):
        ToDolist.setObjectName("ToDolist")
        ToDolist.resize(431, 399)
        self.centralwidget = QtWidgets.QWidget(ToDolist)
        self.centralwidget.setObjectName("centralwidget")

        self.List_item_pb = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.add_task())
        self.List_item_pb.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.List_item_pb.setObjectName("List_item_pb")

        self.Delete_item_pb = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.delete_task())
        self.Delete_item_pb.setGeometry(QtCore.QRect(100, 70, 91, 31))
        self.Delete_item_pb.setObjectName("Delete_item_pb")

        self.Clear_list_pb = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clear_list())
        self.Clear_list_pb.setGeometry(QtCore.QRect(190, 70, 111, 31))
        self.Clear_list_pb.setCheckable(False)
        self.Clear_list_pb.setObjectName("Clear_list_pb")

        self.Add_item = QtWidgets.QLineEdit(self.centralwidget)
        self.Add_item.setGeometry(QtCore.QRect(20, 10, 391, 51))
        self.Add_item.setObjectName("Add_item")

        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(20, 110, 391, 231))
        self.mylist_listWidget.setObjectName("mylist_listWidget")

        self.add_to_db_pb = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.save_db())
        self.add_to_db_pb.setGeometry(QtCore.QRect(300, 70, 111, 31))
        self.add_to_db_pb.setCheckable(False)
        self.add_to_db_pb.setObjectName("add_to_db_pb")


        ToDolist.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ToDolist)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 26))
        self.menubar.setObjectName("menubar")
        ToDolist.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ToDolist)
        self.statusbar.setObjectName("statusbar")
        ToDolist.setStatusBar(self.statusbar)

        self.retranslateUi(ToDolist)
        QtCore.QMetaObject.connectSlotsByName(ToDolist)


    def add_task(self):
            item = self.Add_item.text()  # grabbing the item from the list box
            self.mylist_listWidget.addItem(item)
            # clearing the item box for new item
            self.Add_item.setText("")


    def delete_task(self):
            # grab the current task
            clicked = self.mylist_listWidget.currentRow()  # this code gives the index of the line selected
            # self.Add_item.setText(str(clicked))
            self.mylist_listWidget.takeItem(clicked)

    def clear_list(self):
            self.mylist_listWidget.clear()

    def save_it(self):
        items = []
        #loop through the list and store it in the list - items
        for index in range(self.mylist_listWidget.count()):#the for loop will append the items in the list
            items.append(self.mylist_listWidget.item(index))#to access the item

        for item in items:
            print(item.text())#this will print all the elements in the terminal

    def retranslateUi(self, ToDolist):
        _translate = QtCore.QCoreApplication.translate
        ToDolist.setWindowTitle(_translate("ToDolist", "MainWindow"))
        self.List_item_pb.setText(_translate("ToDolist", "Add task"))
        self.Delete_item_pb.setText(_translate("ToDolist", "Delete Task"))
        self.Clear_list_pb.setText(_translate("ToDolist", "Clear List"))
        self.add_to_db_pb.setText(_translate("ToDolist", "Add to database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToDolist = QtWidgets.QMainWindow()
    ui = Ui_ToDolist()
    ui.setupUi(ToDolist)
    ToDolist.show()
    sys.exit(app.exec_())
